name: journey_to_advanced_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_bloc: ^8.1.6

  # Code generator (mainly used with cubit & retrofit).
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4

  # Splash Screen
  flutter_native_splash: ^2.4.3

  # Responsive Design
  flutter_screenutil: ^5.9.3

  # Networking
  dio: ^5.7.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.5

  # Shimmer effect
  shimmer: ^3.0.0

  # Dependency Injection
  get_it: ^8.0.2

  # Local Storage
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2

  # Load and cache network images
  cached_network_image: ^3.4.1

  # SVG library for rendering painting
  flutter_svg: ^2.0.15

  # Firebase
  firebase_core: ^3.8.0


dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
